### PR TITLE
New Ad Space Content

### PR DESCRIPTION
**Pull request by jessieliz**
New Ad Space Content

### CODE REVIEW

**Comment by jessieliz** [comment]
Shrunk the title just a bit.

**Comment by jessieliz** [comment]
Shrunk the title.  But looks like I can't merge without your approval.

Jessica Gullickson
Vice President of Operations
TrackAbout Inc. <http://www.trackabout.com>
1-800-960-1510 or 412-269-1872 ext 128

**Comment by jessieliz** [comment]
There was a conflict.  I think I've resolved it, but now it's asking for your approval again.

**Comment by silverl** [comment]
Squashing and merging.

**Pull request merged**
